from setuptools import setup, find_packages

setup(
    name="GestureKey", 
    version="0.1.0",
    author="Ángel Gabriel Crispín Valdivia",
    author_email="contacto@angelcrispin.dev",
    description="Aplicación de reconocimiento de gestos de mano",
    url="https://github.com/FaureGalliard/GestureKey",  
    packages=find_packages(),  
    python_requires=">=3.11",
    install_requires=[
        "absl-py==2.4.0",
        "altgraph==0.17.5",
        "attrs==25.4.0",
        "cffi==2.0.0",
        "comtypes==1.4.16",
        "contourpy==1.3.3",
        "cycler==0.12.1",
        "flatbuffers==25.12.19",
        "fonttools==4.61.1",
        "joblib==1.5.3",
        "kiwisolver==1.4.9",
        "matplotlib==3.10.8",
        "mediapipe==0.10.9",
        "MouseInfo==0.1.3",
        "numpy==2.4.2",
        "opencv-contrib-python==4.13.0.92",
        "opencv-python==4.13.0.92",
        "packaging==26.0",
        "pandas==3.0.1",
        "pefile==2024.8.26",
        "pillow==12.1.1",
        "protobuf==3.20.3",
        "PyAutoGUI==0.9.54",
        "pycparser==3.0",
        "PyGetWindow==0.0.9",
        "pygrabber==0.2",
        "pyinstaller==6.19.0",
        "pyinstaller-hooks-contrib==2026.3",
        "PyMsgBox==2.0.1",
        "pynput==1.8.1",
        "pyparsing==3.3.2",
        "pyperclip==1.11.0",
        "PyQt6==6.10.2",
        "PyQt6-Qt6==6.10.2",
        "PyQt6_sip==13.11.0",
        "PyRect==0.2.0",
        "PyScreeze==1.0.1",
        "pystray==0.19.5",
        "python-dateutil==2.9.0.post0",
        "python-dotenv==1.2.1",
        "pytweening==1.2.0",
        "pywin32==311",
        "pywin32-ctypes==0.2.3",
        "scikit-learn==1.8.0",
        "scipy==1.17.0",
        "six==1.17.0",
        "sounddevice==0.5.5",
        "threadpoolctl==3.6.0",
        "tzdata==2025.3",
    ],
    entry_points={
        "console_scripts": [
            "gesturekey=gesturekey.main:main",  
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: Microsoft :: Windows",
    ],
)