# =========================
# CONSTANTES
# =========================

DEADZONE = 0.015
SMOOTHING = 0.7
SCROLL_SENS = 1.2
VOLUME_SENS = 1.0
ZOOM_SENS = 1.5
PAUSE_MIN_TIME = 0.2
MUTE_MAX_TIME = 1.0
COOLDOWN = 0.6
SCROLL_DEADZONE = 0.03
SCROLL_TRIGGER = 0.08
SCROLL_COOLDOWN = 0.15